(function(){
  const root=document.querySelector('#view-root'),state=window.portfolioState;let selected='all';
  const money=n=>(n<0?'−':'')+'¥'+Math.abs(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
  const setText=(n,t)=>{if(n&&n.textContent!==t)n.textContent=t},setClass=(n,c)=>{if(n&&n.className!==c)n.className=c};
  function data(){const accounts=selected==='all'?Object.values(state.accounts):[state.accounts[selected]].filter(Boolean),funds=accounts.flatMap(a=>a.funds||[]),total=funds.reduce((s,f)=>s+Number(f.amount||0),0),profit=funds.reduce((s,f)=>s+Number(Number.isFinite(f.holdingProfit)?f.holdingProfit:(f.amount||0)*(f.hold||0)),0),cost=total-profit,rate=cost?profit/cost:0;return{total,profit,rate}}
  function updateCard(){const box=root.querySelector('.kpis');if(!box)return;const items=box.querySelectorAll('.kpi');if(items.length<4)return;const d=data(),label=items[0].querySelector('.kpi-label');setText(label,selected==='all'?'全部账户总资产':'当前账户总资产');setText(items[0].querySelector('.kpi-value'),money(d.total));setText(items[1].querySelector('.kpi-value'),'¥0.00');setText(items[1].querySelector('.kpi-sub'),'0.00%');setText(items[2].querySelector('.kpi-value'),money(d.profit));setText(items[2].querySelector('.kpi-sub'),(d.rate*100).toFixed(2)+'%');setText(items[3].querySelector('.kpi-value'),money(d.profit));setText(items[3].querySelector('.kpi-sub'),(d.rate*100).toFixed(2)+'%');[items[1],items[2],items[3]].forEach(i=>{setClass(i.querySelector('.kpi-value'),'kpi-value');setClass(i.querySelector('.kpi-sub'),'kpi-sub')})}
  function updateTabs(){root.querySelectorAll('.account-segment').forEach(b=>b.classList.toggle('active',b.dataset.accountTab===selected))}
  function ensure(){const box=root.querySelector('.kpis');if(!box)return;if(selected!=='all'&&!state.accounts[selected])selected=state.getActive()||'all';let tabs=root.querySelector('.account-segmented');if(!tabs){tabs=document.createElement('div');tabs.className='account-segmented';tabs.setAttribute('role','tablist');tabs.innerHTML='<button class="account-segment" data-account-tab="all">总览</button>'+Object.keys(state.accounts).map(n=>'<button class="account-segment" data-account-tab="'+n.replace(/"/g,'&quot;')+'">'+n.replace(/（朋友账户）/,'')+'</button>').join('');box.before(tabs)}updateTabs();updateCard()}
  root.addEventListener('click',e=>{const tab=e.target.closest('[data-account-tab]');if(!tab)return;selected=tab.dataset.accountTab;if(selected!=='all'&&state.accounts[selected])state.setActive(selected);updateTabs();updateCard()});
  root.addEventListener('click',e=>{const row=e.target.closest('.account-section .account-card[data-account]');if(!row||row.classList.contains('account-edit-row'))return;e.preventDefault();e.stopImmediatePropagation();selected=row.dataset.account;state.setActive(selected);updateTabs();updateCard()},true);
  new MutationObserver(ensure).observe(root,{childList:true,subtree:true});ensure();
})();
